"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var StudentScoreManagement_1 = require("./StudentScoreManagement");
var studentManager = new StudentScoreManagement_1.StudentScoreManagement();
studentManager.insertFirst('dung', 9);
studentManager.insertFirst('trung', 7);
studentManager.insertFirst('thinh', 4);
console.log(studentManager.totalStudentsFail());
console.log(studentManager.listStudentMaxScore());
console.log(studentManager.findByName("dung"));
