"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var circle = new Circle_1.Circle(3.5, "blue", false);
console.log(circle);
console.log(circle.getArea());
console.log(circle.getPerimeter());
console.log(circle.toString());
var Retangle_1 = require("./Retangle");
var rectangle = new Retangle_1.Rectangle(2.8, 3.8, "orange", true);
console.log(rectangle);
console.log(rectangle.getArea());
console.log(rectangle.getPerimeter());
console.log(rectangle.toString());
var shape_1 = require("./shape");
var shape = new shape_1.Shape("blue", false);
console.log(shape);
console.log(shape.toString());
var Square_1 = require("./Square");
var square = new Square_1.Square(5.8, "yellow", true);
console.log(square);
console.log(square.toString());
