"use strict";
exports.__esModule = true;
var stack_1 = require("./stack");
var stack = new stack_1.Stack();
stack.push(1);
stack.push(2);
stack.push(3);
stack.push(4);
stack.pop();
stack.size();
console.log(stack);
